apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saida1036/saida/tree/main/guestbook1.git
    targetRevision: HEAD
    path: guestbook1
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook1

  
  syncPolicy:
   syncOptions:
   - CreateNamespace=true

   automated:
     selfHeal: true
     prune: true